### PR TITLE
565

### PR DESCRIPTION
**Pull request by YuriDio**
Merging changes from @lastcoolnameleft and fixing conflicts

### CODE REVIEW

**Comment by jomolnar** [comment]
@YuriDio This looks positive, but I don't see an option to merge this pull request.

**Comment by YuriDio** [comment]
@jomolnar since @lastcoolnameleft owns it, he will have the option to merge can you merge it. @lastcoolnameleft do you see the option to merge it?

**Comment by BryanLa** [comment]
@jomolnar - I'm discussing w/Yuri as well. Just waiting on @lastcoolnameleft to merge his PR...

**Comment by lastcoolnameleft** [comment]
Sorry for the delay.  Just merged.

**Comment by BryanLa** [comment]
Thanks @lastcoolnameleft !

**Pull request merged**
